"""empty message

Revision ID: 486a08f1700e
Revises: de66b9e734a0
Create Date: 2017-01-26 17:20:15.682000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486a08f1700e'
down_revision = 'de66b9e734a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'request_admin_id_fkey', 'request', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'request_admin_id_fkey', 'request', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###
