"""empty message

Revision ID: de66b9e734a0
Revises: 669520b92ead
Create Date: 2017-01-26 16:21:03.686000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de66b9e734a0'
down_revision = '669520b92ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'request_admin_id_fkey', 'request', type_='foreignkey')
    op.drop_constraint(u'request_facility_id_fkey', 'request', type_='foreignkey')
    op.drop_constraint(u'request_user_id_fkey', 'request', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'request_user_id_fkey', 'request', 'users', ['user_id'], ['id'])
    op.create_foreign_key(u'request_facility_id_fkey', 'request', 'facilities', ['facility_id'], ['id'])
    op.create_foreign_key(u'request_admin_id_fkey', 'request', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###
